### ISSUE TITLE
Yari doesn't show gems

### ISSUE THREAD

**Issue by blazeeboy** [hron/yari.el#11]
Hello i noticed that using Yari is not showing any documentation from outside ruby core/stdlib.
so searching for rails doesn't show any results, i think it's because of RVM maybe? i have `rvm 1.26.11` and installed yari from melpa.org
is there something i'm missing? or this is the normal behaviour ?

**Comment by hron** [comment]
Most likely this is because the documentation was not generated during gems installation. If you use bundler this is the default behavior. In other words when you install gems with `bundle install` bundler passes --no-ri to `gem install` command.

You have to generate documentation manually. It can be done with help of rvm command:

```bash
$ rvm docs generate-ri
```

**Comment by blazeeboy** [comment]
No, it's not working at all, i have run the command twice, once inside the project directory (because it uses an older ruby version) and another one outside the project directory and no use, i tried to search `ActiveSupport` and nothing appear

**Comment by blazeeboy** [comment]
I think this issue is related somehow to using this combination (RVM + ZSH), maybe Yari is using Bash?!, i don't know but i still can't use Yari, and i have no idea how to debug it, any ideas would be appreciated.

**Comment by hron** [comment]
yari.el runs ruby to get list of ri pages, it also runs `ri` command to get documentation page. You should run terminal and try to execute `ri ActiveRecord::Base`. If ri can't find this page, yari doesn't show it too.

As I said before, my best guess is that ri pages are not generated. Bundler doesn't not generate these pages during gems install.

**Comment by blazeeboy** [comment]
Thanks for your prompt response, I executed `ri ActiveRecord::Base > outputfile` and the output was correct https://gist.github.com/blazeeboy/dfea554852dd1ed2c653
but executing the Yari help `F1` while selecting `ActiveRecord::Base` did return any result as in screenshot
<img width="802" alt="screen shot 2016-02-20 at 19 30 06" src="https://cloud.githubusercontent.com/assets/54403/13198437/eb8ea09a-d808-11e5-99c5-66ee52b9f078.png">

**Comment by hron** [comment]
Did you run emacs from the same terminal where you have got the correct output for `ri ActiveRecord::Base`? Do you use rvm.el?

**Comment by blazeeboy** [comment]
I use Emacs from GUI not terminal, i tried to run it from terminal now and it seem to work from there, so the problem lies in GUI.

**Comment by hron** [comment]
Yes, when you run it from GUI the environment is not populated with right values from RVM. You can add desktop icon and run emacs with something like this: `bash -l -c "cd ~/you-project-dir; emacs"`
